//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_KATEGORILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_KATEGORILER()
        {
            this.TBL_URUNLER = new HashSet<TBL_URUNLER>();
        }
    
        public short KATEGORIID { get; set; }

        [Required(ErrorMessage = "Kategori adý boþ geçilemez, lütfen bu alaný doldurun.")]
        [StringLength(50, ErrorMessage = "Bu alana en fazla 50 karakter girilebilir, lütfen kontrol edin.")]
        public string KATEGORIAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_URUNLER> TBL_URUNLER { get; set; }
    }
}
